// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QuoteProvider is an autogenerated mock type for the quoteProvider type
type QuoteProvider struct {
	mock.Mock
}

type QuoteProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *QuoteProvider) EXPECT() *QuoteProvider_Expecter {
	return &QuoteProvider_Expecter{mock: &_m.Mock}
}

// GetQuote provides a mock function with no fields
func (_m *QuoteProvider) GetQuote() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QuoteProvider_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type QuoteProvider_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
func (_e *QuoteProvider_Expecter) GetQuote() *QuoteProvider_GetQuote_Call {
	return &QuoteProvider_GetQuote_Call{Call: _e.mock.On("GetQuote")}
}

func (_c *QuoteProvider_GetQuote_Call) Run(run func()) *QuoteProvider_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QuoteProvider_GetQuote_Call) Return(_a0 string) *QuoteProvider_GetQuote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QuoteProvider_GetQuote_Call) RunAndReturn(run func() string) *QuoteProvider_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuoteProvider creates a new instance of QuoteProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuoteProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuoteProvider {
	mock := &QuoteProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
