// Code generated by ifacemaker; DO NOT EDIT.

package pow

// PoW ...
type PoW interface {
	// GenerateChallenge creates a random challenge string.
	GenerateChallenge() string
	// ValidateChallenge checks if the provided solution meets the required difficulty.
	ValidateChallenge(challenge, solution string) bool
}
